'\" t
.\"     Title: footermilter.jar
.\"    Author: Klaus Tachtler
.\" Generator: Asciidoctor 2.0.21
.\"      Date: 2024-05-01
.\"    Manual: FooterMilter.jar Manual
.\"    Source: FooterMilter.jar 1.2.
.\"  Language: English
.\"
.TH "FOOTERMILTER.JAR" "1" "2024-05-01" "FooterMilter.jar 1.2." "FooterMilter.jar Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
FooterMilter.jar \- Java implementation of the Sendmail Milter protocol based on the project of org.nightcode.jmilter from dmitry@nightcode.org to insert a footer/disclaimer at the end of the body of an email.
.SH "SYNOPSIS"
.sp
\fB[\fIPATH_TO\fP]/java \-jar [\fIPATH_TO\fP]/FooterMilter.jar [\fIOPTION\fP] [\-h] [\-v] [\-d] \fIFILE\fP [\-c [\fIPATH_TO_CONFIG_FILE\fP]/[\fINAME_OF_CONFIG_FILE\fP]]\fP
.SH "DESCRIPTION"
.sp
The FooterMilter.jar(1) is the Java implementation of the Sendmail Milter protocol based on the project of org.nightcode.jmilter from \c
.MTO "dmitry\(atnightcode.org" "" ""
to insert a footer/disclaimer at the end of the body of an email.
.sp
The \fIOPTION\fP \fB\-c, \-\-config\fP is \fIREQUIRED\fP and the \fIFILE\fP [\fIPATH_TO_CONFIG_FILE\fP]/[\fINAME_OF_CONFIG_FILE\fP]] is \fIalso\fP \fIREQUIRED\fP for running the program.
.SH "OPTIONS"
.SS "Configuration parameter"
.sp
\fB\-c, \-\-config\fP[\fIPATH_TO_CONFIG_FILE\fP]/[\fINAME_OF_CONFIG_FILE\fP]]
.RS 4
[REQUIRED] Path and name of the config file
.RE
.SS "Debugging"
.sp
\fB\-d, \-\-debug\fP
.RS 4
DEBUG mode with runtime output
.RE
.SS "Program Information"
.sp
\fB\-h, \-\-help\fP
.RS 4
Print usage information
.RE
.sp
\fB\-v, \-\-version\fP
.RS 4
Version of the program
.RE
.SH "CONFIGURATION FILE"
.sp
The main configuration file of the FooterMilter \- \fBfootermilter.ini\fP includes all settings for
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
the start and the start parameters \- section \fB\f(CR[server]\fP\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
the configuration of the footer section to be used \fB\f(CR[footer]\fP\fP
.RE
.SS "Section: [service]"
.sp
The following parameters can be set in the \fBsection \f(CR[server]\fP\fP:
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 1. Table Section: [service]
.TS
allbox tab(:);
ltB ltB ltB.
T{
.sp
Parameter
T}:T{
.sp
Default value
T}:T{
.sp
Description
T}
.T&
lt lt lt.
T{
.sp
\f(CRlisten\fP
T}:T{
.sp
\f(CR127.0.0.1\fP
T}:T{
.sp
IPv4\-address or hostname where the service/daemon should be reachable
T}
T{
.sp
\f(CRport\fP
T}:T{
.sp
\f(CR10099\fP
T}:T{
.sp
Port where the service/daemon should be reachable
T}
.TE
.sp
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Warning
.ps -1
.br
.sp
If \fBDEBUG\fP logging is desired for troubleshooting purposes, this can be achieved with the [\fIOPTION\fP] \fB\-d\fP in the start script or with a manual start.
.sp .5v
.RE
.SS "Section: [footer]"
.sp
In the \fB[footer] section(s) multiple configurations are possible and desired, but please note the following:\fP
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Each section [footer] must begin with the word footer.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Each section [footer] must have a unambiguous designation.
.RE
.sp
\fIExamples:\fP
.sp
.if n .RS 4
.nf
.fam C
    [footer: default]
    [localpart@domain.tld]
    [footer 001]
    [footer\-default]
    [footer]
.fam
.fi
.if n .RE
.sp
The following parameters can be set in the section(s) [footer]:
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 2. Table Section: [footer]
.TS
allbox tab(:);
ltB ltB ltB.
T{
.sp
Parameter
T}:T{
.sp
Default value
T}:T{
.sp
Description
T}
.T&
lt lt lt.
T{
.sp
\f(CRenabled\fP
T}:T{
.sp
\f(CRtrue\fP
T}:T{
.sp
Should this [footer] section be active
T}
T{
.sp
\f(CRfrom\fP
T}:T{
.sp
\f(CRuser@example.com\fP or \f(CR@example.com\fP
T}:T{
.sp
E\-Mail\-Address or Domain with \*(Aq@\*(Aq\-sign in front
T}
T{
.sp
\f(CRtext\fP
T}:T{
.sp
\f(CR\-\-\fP
T}:T{
.sp
Footer for the Content\-Type \- text/plain
T}
T{
.sp
\f(CRhtml\fP
T}:T{
.sp
\f(CR\-\-\fP
T}:T{
.sp
Footer for the Content\-Type \- text/html
T}
.TE
.sp
.sp
The following special feature applies to the
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBParameter:\fP \f(CRfrom\fP
.RE
.sp
If \f(CR@Domain.tld\fP is entered here instead of a complete e\-mail address, this Footer will be attached if no e\-mail address applies to other Footers.
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Warning
.ps -1
.br
.sp
\f(CR@Domain.tld\fP is the standard footer for this domain!
.sp .5v
.RE
.sp
\fIExamples:\fP
.sp
.if n .RS 4
.nf
.fam C
    user@example.com \- e\-mail address
    @example.com \- Default for this domain if no email address matches.
    @sub.example.com \- Default for this sub\-domain if no email address matches.
.fam
.fi
.if n .RE
.sp
The following special feature applies to the
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBParameter:\fP \f(CRtext\fP and
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBParameter:\fP \f(CRhtml\fP
.RE
.sp
For better readability during the configuration of the parameters text and html, e.g. add a
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR\(rs\fP \fB(backslash)\fP
.RE
.sp
\fBat the END of a line.\fP
.sp
In addition, subsequent \fB"Escape" sequences\fP can be used to increase readability when configuring the respective \fBFooter\fP.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 3. Table Section: [footer] \- "Escape" sequences
.TS
allbox tab(:);
ltB ltB.
T{
.sp
Escape sequence
T}:T{
.sp
Description
T}
.T&
lt lt.
T{
.sp
\f(CR\(rst\fP
T}:T{
.sp
Insert a tabulator into the text at this point.
T}
T{
.sp
\f(CR\(rsb\fP
T}:T{
.sp
Add a "backspace" to the text at this point.
T}
T{
.sp
\f(CR\(rsn\fP
T}:T{
.sp
Add a new line to the text at this point.
T}
T{
.sp
\f(CR\(rsr\fP
T}:T{
.sp
Add a carriage return code to the text at this point.
T}
T{
.sp
\f(CR\(rsf\fP
T}:T{
.sp
Add a form feed to the text at this point.
T}
T{
.sp
\f(CR\(rs\*(Aq\fP
T}:T{
.sp
Insert a single quotation mark into the text at this point.
T}
T{
.sp
\f(CR\(rs"\fP
T}:T{
.sp
Insert a double quotation mark in the text at this point.
T}
T{
.sp
\f(CR\(rs\(rs\fP
T}:T{
.sp
Add a "backslash" character to the text at this point.
T}
.TE
.sp
.sp
\fIExamples:\fP
.sp
\fBtext/plain\fP
.sp
.if n .RS 4
.nf
.fam C
\-\- \(rs
\(rsn\(rs
\(rsn\(rs
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\(rsn\(rs
Footer default\(rsn\(rs
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\(rsn\(rs
\(rsn
.fam
.fi
.if n .RE
.sp
\fBtext/html\fP
.sp
.if n .RS 4
.nf
.fam C
<br\(rs>\(rsn\(rs
<br\(rs>\(rsn\(rs
<span style=\(rs"font\-family:monospace; color:#000000\(rs">\-\-&nbsp;</span><br>\(rsn\(rs
<br\(rs>\(rsn\(rs
<span style=\(rs"font\-family:monospace; color:#000000\(rs">Footer default</span><br>\(rsn\(rs
<br\(rs>\(rsn\(rsn
.fam
.fi
.if n .RE
.SS "EXAMPLE"
.sp
Finally as an \fBexample\fP a \fBcomplete configuration file\fP:
.sp
.if n .RS 4
.nf
.fam C
################################################################################
# JMilter Server for connections from an MTA to add a footer.
#
# JMilter is an Open Source implementation of the Sendmail milter protocol, for
# implementing milters in Java that can interface with the Sendmail or Postfix
# MTA.
#
# Java implementation of the Sendmail Milter protocol based on the project of
# org.nightcode.jmilter from dmitry@nightcode.org.
#
# @author Klaus Tachtler. <klaus@tachtler.net>
#
#         Homepage : http://www.tachtler.net
#
#         Licensed under the Apache License, Version 2.0 (the "License"); you
#         may not use this file except in compliance with the License. You may
#         obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE\-2.0
#
#         Unless required by applicable law or agreed to in writing, software
#         distributed under the License is distributed on an "AS IS" BASIS,
#         WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#         implied. See the License for the specific language governing
#         permissions and limitations under the License..
#
# Copyright (c) 2024 Klaus Tachtler. All Rights Reserved.
# Klaus Tachtler. <klaus@tachtler.net>
# http://www.tachtler.net
#
################################################################################


################################################################################
# [server] section \- Start configuration for the server.
################################################################################

[server]

# IPv4 address or hostname to listen.
listen = 127.0.0.1

# Port to listen.
port = 10099

################################################################################
# [footer] section \- Configuration of the footers to be used.
################################################################################
#
# !IMPORTANT: Every section
#             a.) must start with the word: footer
#             b.) must have an unique name
#
# EXAMPLES:   [footer: default], [footer: localpart@domain.tld], [footer: 001]
#
# ==============================================================================
#
# from field: If inside a [footer]\-section the from field was defined with the
#             following syntax: @domain.tld \-> NO localpart! <\-
#             this will be used as DEFAULT for the domain, if no email address
#             will match!
#
# EXAMPLE:    from = @example.com
#
# ==============================================================================
#
# text/html : For a better configuration view for the text and html fields, it\*(Aqs
#             possible to use a single \(rs (backslash) at the end of the line!
#
# EXAMPLE:    text = \-\- \(rs
#             first word \(rs
#             second word \(rs
#             last word.
#
# SAME AS:    text = \-\- first word second word last word.
#
# ==============================================================================
#
# escape\*(Aqs  : Some escape sequences can be used, for more well formatted output!
#             Escape sequences description:
#
#             \(rst     Insert a tab in the text at this point.
#             \(rsb     Insert a backspace in the text at this point.
#             \(rsn     Insert a newline in the text at this point.
#             \(rsr     Insert a carriage return in the text at this point.
#             \(rsf     Insert a formfeed in the text at this point.
#             \(rs\*(Aq     Insert a single quote character in the text at this point.
#             \(rs"     Insert a double quote character in the text at this point.
#             \(rs\(rs     Insert a backslash character in the text at this point.
#
################################################################################

[footer: @example.com]

# Enable this footer.
enabled = true

# Email "mail from:" for generating the footer.
from = @example.com

# Footer for text/plain.
text = \-\- \(rs
\(rsn\(rs
\(rsn\(rs
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\(rsn\(rs
Footer default\(rsn\(rs
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\(rsn\(rs
\(rsn

# Footer for text/html.
html = <br\(rs>\(rsn\(rs
<br\(rs>\(rsn\(rs
<span style=\(rs"font\-family:monospace; color:#000000\(rs">\-\-&nbsp;</span><br>\(rsn\(rs
<br\(rs>\(rsn\(rs
<span style=\(rs"font\-family:monospace; color:#000000\(rs">Footer default</span><br>\(rsn\(rs
<br\(rs>\(rsn\(rsn

################################################################################

[footer: user@example.com]

# Enable this footer.
enabled = true

# Email "mail from:" for generating the footer.
from = user@example.com

# Footer for text/plain.
text = \-\- \(rsn\(rsn\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\(rsnFooter user\(rsn\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\(rsn\(rsn

# Footer for text/html.
html = <br\(rs>\(rsn<br\(rs>\(rsn<span style=\(rs"font\-family:monospace; color:#000000\(rs">\-\-&nbsp;</span><br>\(rsn<br\(rs>\(rsn<span style=\(rs"font\-family:monospace; color:#000000\(rs">Footer user</span><br>\(rsn<br\(rs>\(rsn\(rsn

################################################################################
.fam
.fi
.if n .RE
.SH "ENVIRONMENT"
.sp
\fIThere is only one dependency for the execution of FooterMilter\fP:
.sp
Running \fBJava installation e.g. OpenJDK\fP from \fBversion 1.8 or higher\fP.
.SH "EXIT STATUS"
.sp
After the start of the program, the configured IP address and port are listened on, so that an EXIT code is not carried during the runtime. Basically the daemon should set the RETURN code to 0 after termination.
.SH "BUGS"
.sp
Refer to the \fBFooterMilter.jar\fP issue tracker at \c
.URL "https://github.com/tachtler/FooterMilter/issues?q=is%3Aopen" "" "."
.SH "AUTHORS"
.sp
\fBFooterMilter.jar\fP was written by Klaus Tachtler. mailto:klaus@tachtler.net
.sp
\fBorg.nightcode.jmilter\fP was written by Dmitry. mailto:dmitry@nightcode.org
.SH "RESOURCES"
.sp
\fBDokuWiki web site:\fP \c
.URL "https://dokuwiki.tachtler.net/doku.php?id=tachtler:postfix_centos_7_\-_footermilter_einsetzen_footermilter" "" ""
.sp
\fBGit source repository on GitHub:\fP \c
.URL "https://github.com/tachtler/FooterMilter" "" ""
.SH "COPYING"
.sp
Copyright (C) 2024 Klaus Tachtler. Free use of this software is granted under the terms of the Apache License 2.0.
.sp
Apache License Version 2.0, January 2004, \c
.URL "http://www.apache.org/licenses/" "" ""
.SH "AUTHOR"
.sp
Klaus Tachtler